import { ContentPillar, BusinessGoalType, RestaurantType, PrimaryCustomerAction, ContentAsset, ContentPlanItem } from "./db/schema";

export const APP_CONFIG = {
  name: "ContentPilot",
  tagline: "AI Content Strategist for Restaurant Owners",
  githubRepo: "ischeduleit-cmd/contentpilot",
  vercelTeam: "ischeduleit",
  vercelUrl: "https://vercel.com/new?teamSlug=ischeduleit",
  contactEmail: "ischeduleit@gmail.com",
  maxAssetsPerWeek: 50,
  maxFileSizeMB: 50,
};

export const CONTENT_PILLARS: { id: ContentPillar; label: string; description: string }[] = [
  {
    id: "product",
    label: "Product & Menu",
    description: "High-clarity footage and photos showcasing signature dishes, portions, and sizzle.",
  },
  {
    id: "social_proof",
    label: "Social Proof",
    description: "Authentic customer reactions, empty plates, table banter, and live reviews.",
  },
  {
    id: "education",
    label: "Education & Craft",
    description: "Culinary techniques, secret sauces, raw ingredient sourcing, and preparation.",
  },
  {
    id: "behind_the_scenes",
    label: "Behind the Scenes",
    description: "Kitchen rush prep, chef plating, staff culture, and opening routine.",
  },
  {
    id: "community",
    label: "Community & Vibe",
    description: "Dining room atmosphere, regular patrons, local neighborhood culture, and ambiance.",
  },
  {
    id: "promotion",
    label: "Direct Promotion",
    description: "Time-limited combos, lunch specials, holiday packages, and delivery offers.",
  },
];

export const BUSINESS_GOALS: { id: BusinessGoalType; label: string; description: string }[] = [
  {
    id: "increase_lunch_orders",
    label: "Increase Weekday Lunch Orders",
    description: "Target working professionals, corporate teams, and students between 11 AM and 2 PM.",
  },
  {
    id: "promote_menu_item",
    label: "Promote a Specific Menu Item",
    description: "Drive targeted volume toward a high-margin or newly introduced specialty.",
  },
  {
    id: "drive_dine_in",
    label: "Drive Dine-in Foot Traffic",
    description: "Fill tables during off-peak hours and promote the dine-in dining room experience.",
  },
  {
    id: "build_trust",
    label: "Build Trust & Social Proof",
    description: "Showcase customer satisfaction, cleanliness, and food quality to win first-time buyers.",
  },
  {
    id: "increase_awareness",
    label: "Increase Local Brand Awareness",
    description: "Expand discovery among nearby diners who have never ordered before.",
  },
  {
    id: "increase_engagement",
    label: "Boost Engagement & Community",
    description: "Stimulate comments, shares, and culinary conversations on Instagram & TikTok.",
  },
  {
    id: "promote_event",
    label: "Promote Weekend Special or Event",
    description: "Pack the house for weekend DJ sets, live music, brunch sessions, or tastings.",
  },
  {
    id: "other",
    label: "Custom Business Goal",
    description: "Tailor the plan around a custom marketing objective.",
  },
];

export const RESTAURANT_TYPES: { id: RestaurantType; label: string }[] = [
  { id: "restaurant", label: "Casual Dining & Restaurant" },
  { id: "fast_food", label: "Quick Service & Fast Food" },
  { id: "cafe_bakery", label: "Café, Bakery & Pastry" },
  { id: "cloud_kitchen", label: "Cloud Kitchen & Delivery Brand" },
  { id: "bar_lounge", label: "Bar, Grill & Lounge" },
  { id: "other", label: "Other Food Service" },
];

export const PRIMARY_ACTIONS: { id: PrimaryCustomerAction; label: string }[] = [
  { id: "order_delivery", label: "Order Food for Delivery" },
  { id: "whatsapp_order", label: "Send WhatsApp / Direct Message to Order" },
  { id: "dine_in", label: "Visit Location for Dine-in" },
  { id: "table_reservation", label: "Book a Table in Advance" },
  { id: "brand_discovery", label: "Follow & Discover the Restaurant" },
  { id: "other", label: "Other Action" },
];

/**
 * Benchmark Dataset: Ovie's Kitchen (Akure, Ondo State)
 * Used for automated verification and default live demonstration
 */
export const BENCHMARK_RESTAURANT = {
  id: "rest-ovie",
  name: "Ovie's Kitchen",
  location: "Akure, Ondo State",
  type: "restaurant" as RestaurantType,
  targetAudience: "Bankers, civil servants, 9-to-5 corporate workers, and university students.",
  primaryAction: "whatsapp_order" as PrimaryCustomerAction,
  activeGoal: {
    goal: "increase_lunch_orders" as BusinessGoalType,
    description: "Increase delivery orders for corporate lunch combos from Monday to Thursday.",
  },
};

export const SAMPLE_BENCHMARK_ASSETS: ContentAsset[] = [
  {
    id: "ast-01",
    restaurantId: "rest-ovie",
    fileUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&auto=format&fit=crop&q=80",
    fileName: "smoky_party_jollof_pot.mp4",
    mediaType: "video/mp4",
    aiDescription: "Steaming party jollof rice pot with visible smoke, fried plantains, and grilled chicken drumstick.",
    contentType: "Signature Dish Video",
    contentPillar: "product",
    objective: "conversion",
    suggestedPlatform: "both",
    confidence: 0.96,
    processingStatus: "ready",
    createdAt: "2026-10-06T10:00:00Z",
  },
  {
    id: "ast-02",
    restaurantId: "rest-ovie",
    fileUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=80",
    fileName: "customer_first_bite_reaction.mp4",
    mediaType: "video/mp4",
    aiDescription: "Corporate customer in business wear taking first bite of peppered beef and nodding in approval.",
    contentType: "Diner Reaction Clip",
    contentPillar: "social_proof",
    objective: "trust",
    suggestedPlatform: "both",
    confidence: 0.93,
    processingStatus: "ready",
    createdAt: "2026-10-06T10:05:00Z",
  },
  {
    id: "ast-03",
    restaurantId: "rest-ovie",
    fileUrl: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&auto=format&fit=crop&q=80",
    fileName: "firewood_sauce_preparation.mp4",
    mediaType: "video/mp4",
    aiDescription: "Chef stirring slow-simmered tomato and scotch bonnet reduction in heavy commercial wok.",
    contentType: "Culinary Technique",
    contentPillar: "education",
    objective: "trust",
    suggestedPlatform: "tiktok",
    confidence: 0.91,
    processingStatus: "ready",
    createdAt: "2026-10-06T10:10:00Z",
  },
  {
    id: "ast-04",
    restaurantId: "rest-ovie",
    fileUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
    fileName: "lunch_rush_plating_line.mp4",
    mediaType: "video/mp4",
    aiDescription: "Kitchen team rapidly packaging 15 takeaway foil packs for corporate courier pickup at 11:45 AM.",
    contentType: "Rush Packaging Line",
    contentPillar: "behind_the_scenes",
    objective: "conversion",
    suggestedPlatform: "both",
    confidence: 0.94,
    processingStatus: "ready",
    createdAt: "2026-10-06T10:15:00Z",
  },
  {
    id: "ast-05",
    restaurantId: "rest-ovie",
    fileUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=80",
    fileName: "goat_meat_pepper_soup_bowl.jpg",
    mediaType: "image/jpeg",
    aiDescription: "Close-up macro photo of rich goat meat pepper soup garnished with fresh scent leaves.",
    contentType: "Menu Item Photo",
    contentPillar: "product",
    objective: "conversion",
    suggestedPlatform: "instagram",
    confidence: 0.97,
    processingStatus: "ready",
    createdAt: "2026-10-06T10:20:00Z",
  },
  {
    id: "ast-06",
    restaurantId: "rest-ovie",
    fileUrl: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&auto=format&fit=crop&q=80",
    fileName: "akure_dining_room_patrons.jpg",
    mediaType: "image/jpeg",
    aiDescription: "Warm midday dining room with colleagues sharing lunch combo platters at wooden tables.",
    contentType: "Ambiance Photo",
    contentPillar: "community",
    objective: "awareness",
    suggestedPlatform: "both",
    confidence: 0.89,
    processingStatus: "ready",
    createdAt: "2026-10-06T10:25:00Z",
  },
  {
    id: "ast-07",
    restaurantId: "rest-ovie",
    fileUrl: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&auto=format&fit=crop&q=80",
    fileName: "weekday_combo_box_breakdown.mp4",
    mediaType: "video/mp4",
    aiDescription: "Unboxing of the executive lunch pack: jollof, fried plantain, salad, and chilled zobo drink.",
    contentType: "Offer Breakdown",
    contentPillar: "promotion",
    objective: "conversion",
    suggestedPlatform: "both",
    confidence: 0.95,
    processingStatus: "ready",
    createdAt: "2026-10-06T10:30:00Z",
  },
];

export const BENCHMARK_WEEKLY_PLAN: ContentPlanItem[] = [
  {
    id: "plan-mon",
    contentPlanId: "plan-ovie-w1",
    assetId: "ast-01",
    asset: SAMPLE_BENCHMARK_ASSETS[0],
    scheduledDate: "2026-10-12",
    dayOfWeek: "Monday",
    contentPillar: "product",
    objective: "conversion",
    contentAngle: "Solve the Monday office lunch crisis before the 12 PM meeting rush.",
    instagramHook: "Your Monday lunch dilemma is already solved.",
    instagramCaption: "Why face another exhausting Monday wondering where to find honest, piping-hot food? Our firewood jollof is ready to ship straight to your office desk. Order before 12:30 PM to guarantee on-time delivery.",
    instagramCta: "Tap the link in our bio or send us a WhatsApp message at +234-800-OVIE to lock in your lunch.",
    tiktokHook: "POV: It's Monday 12 PM and your lunch is already on your desk.",
    tiktokCaption: "Monday lunch scramble? Never heard of it. Smoky jollof with fried plantains on standby. Link in bio.",
    tiktokCta: "WhatsApp us before 1 PM to claim yours.",
    recommendedTime: "11:30 AM",
    status: "approved",
  },
  {
    id: "plan-tue",
    contentPlanId: "plan-ovie-w1",
    assetId: "ast-02",
    asset: SAMPLE_BENCHMARK_ASSETS[1],
    scheduledDate: "2026-10-13",
    dayOfWeek: "Tuesday",
    contentPillar: "social_proof",
    objective: "trust",
    contentAngle: "Zero actors. Real colleagues in Akure confirming the food speaks for itself.",
    instagramHook: "Watch this before you order lunch anywhere else today.",
    instagramCaption: "We can tell you our peppered beef is tender all day, but nothing speaks clearer than an empty plate. Thank you to the corporate team from Alagbaka for dropping by yesterday afternoon.",
    instagramCta: "Dine in or get it delivered to your office via our WhatsApp order line.",
    tiktokHook: "The face you make when the food actually matches the hype.",
    tiktokCaption: "First bite review from our regular Tuesday lunch crew. Clean plates every time.",
    tiktokCta: "Tap our bio to place today's order.",
    recommendedTime: "12:00 PM",
    status: "approved",
  },
  {
    id: "plan-wed",
    contentPlanId: "plan-ovie-w1",
    assetId: "ast-03",
    asset: SAMPLE_BENCHMARK_ASSETS[2],
    scheduledDate: "2026-10-14",
    dayOfWeek: "Wednesday",
    contentPillar: "education",
    objective: "trust",
    contentAngle: "Showcase the slow-simmered scotch bonnet reduction that separates commercial shortcuts from real craft.",
    instagramHook: "Why our pepper sauce takes 4 hours of slow simmer every morning.",
    instagramCaption: "No artificial bouillon pastes. No rushing. Just fresh plum tomatoes, scotch bonnets, and pure culinary patience. When you taste our food at lunch, this is what you're actually paying for.",
    instagramCta: "Taste the difference in today's executive lunch box. Link in bio.",
    tiktokHook: "The real reason your jollof doesn't hit like restaurant jollof.",
    tiktokCaption: "Step inside the kitchen at 7:30 AM. Fresh ingredients, zero shortcuts.",
    tiktokCta: "Order your midweek plate before 1:30 PM.",
    recommendedTime: "10:45 AM",
    status: "approved",
  },
  {
    id: "plan-thu",
    contentPlanId: "plan-ovie-w1",
    assetId: "ast-07",
    asset: SAMPLE_BENCHMARK_ASSETS[6],
    scheduledDate: "2026-10-15",
    dayOfWeek: "Thursday",
    contentPillar: "promotion",
    objective: "conversion",
    contentAngle: "Group corporate bundle unboxing: complete desk combo packaging breakdown.",
    instagramHook: "The executive combo that feeds your whole department without breaking budget.",
    instagramCaption: "Midweek energy running low? Our Thursday departmental combo packs include firewood jollof, tender goat meat, freshly fried dodo, and cold zobo. Packed in insulated containers to stay hot.",
    instagramCta: "Send us your department count on WhatsApp before 11:30 AM for express corporate delivery.",
    tiktokHook: "What 5,000 Naira gets you for lunch in Akure right now.",
    tiktokCaption: "Full unboxing of the Thursday executive combo. Tag a coworker who owes you lunch.",
    tiktokCta: "Link in bio to WhatsApp order.",
    recommendedTime: "11:15 AM",
    status: "approved",
  },
  {
    id: "plan-fri",
    contentPlanId: "plan-ovie-w1",
    assetId: "ast-04",
    asset: SAMPLE_BENCHMARK_ASSETS[3],
    scheduledDate: "2026-10-16",
    dayOfWeek: "Friday",
    contentPillar: "behind_the_scenes",
    objective: "conversion",
    contentAngle: "The 11:45 AM Friday kitchen rush: packaging 25 orders in 12 minutes.",
    instagramHook: "Friday 11:45 AM inside our dispatch line. We don't play with delivery deadlines.",
    instagramCaption: "When your team orders Friday lunch, you want it delivered when hunger strikes, not after your 1 PM meeting has already started. Here is our line packing today's first 25 dispatch boxes.",
    instagramCta: "Order your Friday office celebratory plate now. WhatsApp link in bio.",
    tiktokHook: "How we pack 25 corporate lunch deliveries in under 15 minutes.",
    tiktokCaption: "Friday shift tempo. Hot food moving fast. Akure deliveries on the road.",
    tiktokCta: "Send a message to secure your lunch box.",
    recommendedTime: "11:30 AM",
    status: "approved",
  },
  {
    id: "plan-sat",
    contentPlanId: "plan-ovie-w1",
    assetId: "ast-05",
    asset: SAMPLE_BENCHMARK_ASSETS[4],
    scheduledDate: "2026-10-17",
    dayOfWeek: "Saturday",
    contentPillar: "product",
    objective: "awareness",
    contentAngle: "Weekend slow-down: goat meat pepper soup bowl for dine-in relaxation.",
    instagramHook: "The weekend recovery bowl your body has been asking for all week.",
    instagramCaption: "Five days of corporate spreadsheets are behind you. Come sit down in our dining room, order a fresh pot of steaming goat meat pepper soup, and take your time.",
    instagramCta: "We're open until 10 PM. Walk-ins welcome, or book ahead for large family tables.",
    tiktokHook: "If your Saturday doesn't start with fresh pepper soup, what are you doing?",
    tiktokCaption: "Real goat meat. Hot aromatic broth. Weekend reset in full effect.",
    tiktokCta: "Location in bio. Come say hello.",
    recommendedTime: "1:00 PM",
    status: "approved",
  },
  {
    id: "plan-sun",
    contentPlanId: "plan-ovie-w1",
    assetId: "ast-06",
    asset: SAMPLE_BENCHMARK_ASSETS[5],
    scheduledDate: "2026-10-18",
    dayOfWeek: "Sunday",
    contentPillar: "community",
    objective: "engagement",
    contentAngle: "Sunday family table atmosphere: closing out the week with regular patrons.",
    instagramHook: "Sunday tables are for family, good laughter, and overflowing plates.",
    instagramCaption: "Our dining room on Sunday afternoon is our favorite view of the week. To every family and group of friends who made Ovie's Kitchen their Sunday tradition: thank you for dining with us.",
    instagramCta: "Drop your favorite dish from this week in the comments below.",
    tiktokHook: "The Sunday dining room atmosphere hits different.",
    tiktokCaption: "Full tables, good music, honest food. Have a restful Sunday, Akure.",
    tiktokCta: "Share this with who you're eating with next weekend.",
    recommendedTime: "3:30 PM",
    status: "approved",
  },
];
